# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1114c329f6f77fd37b766a1d2c7dddc9534ac0a52ef73b47b65769709c6bc311ad4d1aa1f3e8222c964515446e54e8c6ba1171a0c35a56cd048221265f61829c

test:
  secret_key_base: 3ead563ac14a2ad173ad5545d3d3109027a5a3c5a2b25a7c17ba0b21b2809aab5f2a7db741f6bc1bd907024227880ee34f9f69fd5aee3a1ff7a73dd84903da29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
